import streamlit as st
import pandas as pd
import plotly.express as px

# 1. PAGE CONFIG
st.set_page_config(page_title="AI Smart Analytics Pro", layout="wide")
st.title("📊 AI-Powered Smart Analytics Dashboard")
st.markdown("### *Digital Accelerator Intelligence Portal*")

# 2. LOAD ENHANCED DATA
@st.cache_data
def load_data():
    # Updated to point to the v2 file generated by your new classifier
    return pd.read_csv("analyzed_feedback_v2.csv")

try:
    df = load_data()

    # 3. EXECUTIVE KPI ROW
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Feedback", len(df))
    col2.metric("Avg. AI Confidence", f"{df['confidence'].mean():.2f}")
    
    # Highlight High Priority Count
    high_priority_count = len(df[df['priority'] == 'High'])
    col3.metric("Urgent Actions", high_priority_count, delta_color="inverse")
    
    col4.metric("Primary Theme", df['theme'].mode()[0])

    st.divider()

    # 4. ANALYTICS ROW
    left_chart, right_chart = st.columns(2)

    with left_chart:
        st.subheader("Sentiment & Confidence Heatmap")
        # Scatter plot showing Sentiment vs Confidence to spot anomalies
        fig_scatter = px.strip(df, x="sentiment", y="confidence", color="priority",
                              title="Feedback Distribution by Sentiment and Priority")
        st.plotly_chart(fig_scatter, use_container_width=True)

    with right_chart:
        st.subheader("Priority Distribution")
        # Bar chart for Priority to show workload distribution
        priority_order = ['Low', 'Medium', 'High']
        fig_priority = px.bar(df['priority'].value_counts().reindex(priority_order).reset_index(), 
                             x='priority', y='count', color='priority',
                             color_discrete_map={'High':'#FF4B4B','Medium':'#FFAA00','Low':'#00CC96'})
        st.plotly_chart(fig_priority, use_container_width=True)

    # 5. FORENSIC ACTION LIST (THE "ACCELERATOR" VIEW)
    st.divider()
    st.subheader("🚨 High Priority Smart Actions")
    high_prio_df = df[df['priority'] == 'High'][['feedback_text', 'theme', 'action_item']]
    if not high_prio_df.empty:
        st.table(high_prio_df)
    else:
        st.success("No high-priority issues detected.")

    # 6. MASTER DATA EXPLORER
    with st.expander("🔍 View All Analyzed Data"):
        st.dataframe(df, use_container_width=True)

except FileNotFoundError:
    st.error("Please run the enhanced classifier.py first to generate 'analyzed_feedback_v2.csv'!")